services:
  # Servicio del backend
  power_backend:
    build:
      context: .
      dockerfile: Dockerfile.backend_security 
    container_name: backend_security_app
    ports:
      - "51002:51002"
    environment:
      SERVICE_NAME: ${SERVICE_NAME}
      K_REVISION: ${K_REVISION}
      LOG_LEVEL: ${LOG_LEVEL}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      JWT_EXPIRATION_MINUTES: ${JWT_EXPIRATION_MINUTES}
      JWT_COOKIE_NAME: ${JWT_COOKIE_NAME}
      JWT_REFRESH_COOKIE_NAME: ${JWT_REFRESH_COOKIE_NAME}
      JWT_COOKIE_SECURE: ${JWT_COOKIE_SECURE}
      JWT_COOKIE_SAMESITE: ${JWT_COOKIE_SAMESITE}
      CSRF_COOKIE_NAME: ${CSRF_COOKIE_NAME}
      CSRF_HEADER_NAME: ${CSRF_HEADER_NAME}
      CSRF_SAFE_METHODS: ${CSRF_SAFE_METHODS}
      CSRF_COOKIE_EXPIRE_MINUTES: ${CSRF_COOKIE_EXPIRE_MINUTES}

#     # networks:
#     #   sorteador:
#     #     ipv4_address: ${HOST_BACKEND} # Utiliza la variable de entorno para definir la IP del contenedor app

# # Definición de redes personalizadas
# networks:
#   sorteador:
#     # driver: ${NETWORK_DRIVER}  # Utiliza la variable de entorno NETWORK_DRIVER
#     # driver_opts:
#     #   parent: ${PARENT}  # Utiliza la variable de entorno PARENT
#     ipam:
#       config:
#         - subnet: ${SUBNET}  # Utiliza la variable de entorno SUBNET
#           gateway: ${GATEWAY}  # Utiliza la variable de entorno GATEWAY
